### ISSUE TITLE
WIP: Implement Norwegian specialized segmenter

### ISSUE THREAD

**Issue by ManyTheFish** [meilisearch/engine-team#26]
TBD @ManyTheFish

**Comment by curquiza** [comment]
Is it correct @ManyTheFish if I close this as "not planned"? I mean, we don't plan to work on this and the norwegian support is not in the search engine?

**Comment by ManyTheFish** [comment]
@curquiza we are on the [engine-team](https://github.com/meilisearch/engine-team) repository, I closed it in favor of https://github.com/meilisearch/product/discussions/523
